---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "EPFL SoOpen 2018"
keywords:    "EPFL, scitas, library, course, coding, documentation"
description: "A course about good coding pratice at EPFL organized by SCITAS and EPFL Library"
source_link: "https://github.com/epfl-scitas/SoOpen"
favicon:     
touch_icon:  
google_analytics_key:  ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false

